spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ProductService
    username: product
    password: pass

  
  config:
    import: optional:configserver:http://localhost:8888
